[toolchain]
anchor_version = "0.31.1"
solana_version = "2.2.13"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
contract = "CsFsWk5NwBuo7bGbryvyujzrtMnz6458EphQ5xytMMpM"

[programs.localnet]
contract = "CsFsWk5NwBuo7bGbryvyujzrtMnz6458EphQ5xytMMpM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
